name: Hourly Python Runner

on:
  schedule:
    - cron: '45 * * * *'  # Runs every hour on the hour (UTC)
  workflow_dispatch:      # Allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
        DRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json" \
          | jq -r --arg ver "$CHROME_VERSION" '.versions[] | select(.version | startswith($ver)) | .version' | head -n 1)
        wget -O chromedriver.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${DRIVER_VERSION}/linux64/chromedriver-linux64.zip"
        unzip chromedriver.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies (if any)
      run: |
        pip install selenium
        pip install beautifulsoup4
        pip install chromedriver-autoinstaller

    - name: Run the Python script
      run: python main.py

    - name: Commit changes
      run: |
        git config user.name "Nonchaloir"
        git config user.email "leow.justin.cs@gmail.com"
        git add index.html
        git commit -m "Auto-update index.html [CI skip]" || echo "No changes to commit"
        git push
