name: Run Hourly Function

on:
  schedule:
    - cron: '0 * * * *' # Runs at the beginning of every hour

jobs:
  run_function:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Or your desired version
      - name: Run the function
        run: main.py # Replace with the path to your script
